// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: '快速开始',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '客户端接入指南',
      items: [{type: 'autogenerated', dirName: 'client-setup'}],
    },
    {
      type: 'category',
      label: '常见问题',
      items: [{type: 'autogenerated', dirName: 'faq'}],
    },
  ],
};

export default sidebars;
