// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: '快速开始',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '部署方式',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: '客户端接入指南',
      items: [{type: 'autogenerated', dirName: 'client-setup'}],
    },
    {
      type: 'category',
      label: '支付网关',
      items: [{type: 'autogenerated', dirName: 'payments'}],
    },
    {
      type: 'category',
      label: '平台使用指南',
      items: [{type: 'autogenerated', dirName: 'usage-guide'}],
    },
    {
      type: 'category',
      label: '管理后台配置',
      items: [{type: 'autogenerated', dirName: 'admin-settings'}],
    },
    {
      type: 'category',
      label: '常见问题',
      items: [{type: 'autogenerated', dirName: 'faq'}],
    },
  ],
};

export default sidebars;
